# Generated by Django 4.2.2 on 2023-07-27 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_alter_productvariant_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagess', to='Store.productvariant'),
        ),
    ]
