# Generated by Django 4.2.1 on 2023-08-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_coupon_coupon_code_coupon_discount_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_price',
            new_name='coupon_price',
        ),
    ]
