# Generated by Django 4.2.1 on 2023-08-11 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_discount_price_coupon_coupon_price'),
        ('order', '0002_order_order_status_order_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_period_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='return_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
